package com.jiayaxing.web.model;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_article.id
     *
     * @mbggenerated Fri Apr 26 16:40:51 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_article.title
     *
     * @mbggenerated Fri Apr 26 16:40:51 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_article.content
     *
     * @mbggenerated Fri Apr 26 16:40:51 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_article.user
     *
     * @mbggenerated Fri Apr 26 16:40:51 CST 2019
     */
    private String user;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_article.id
     *
     * @return the value of shiro_article.id
     *
     * @mbggenerated Fri Apr 26 16:40:51 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_article.id
     *
     * @param id the value for shiro_article.id
     *
     * @mbggenerated Fri Apr 26 16:40:51 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_article.title
     *
     * @return the value of shiro_article.title
     *
     * @mbggenerated Fri Apr 26 16:40:51 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_article.title
     *
     * @param title the value for shiro_article.title
     *
     * @mbggenerated Fri Apr 26 16:40:51 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_article.content
     *
     * @return the value of shiro_article.content
     *
     * @mbggenerated Fri Apr 26 16:40:51 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_article.content
     *
     * @param content the value for shiro_article.content
     *
     * @mbggenerated Fri Apr 26 16:40:51 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_article.user
     *
     * @return the value of shiro_article.user
     *
     * @mbggenerated Fri Apr 26 16:40:51 CST 2019
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_article.user
     *
     * @param user the value for shiro_article.user
     *
     * @mbggenerated Fri Apr 26 16:40:51 CST 2019
     */
    public void setUser(String user) {
        this.user = user;
    }
}