package com.jiayaxing.web.dao;

import com.jiayaxing.web.model.Article;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_article
     *
     * @mbggenerated Fri Apr 26 16:40:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_article
     *
     * @mbggenerated Fri Apr 26 16:40:51 CST 2019
     */
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_article
     *
     * @mbggenerated Fri Apr 26 16:40:51 CST 2019
     */
    int insertSelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_article
     *
     * @mbggenerated Fri Apr 26 16:40:51 CST 2019
     */
    Article selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_article
     *
     * @mbggenerated Fri Apr 26 16:40:51 CST 2019
     */
    int updateByPrimaryKeySelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_article
     *
     * @mbggenerated Fri Apr 26 16:40:51 CST 2019
     */
    int updateByPrimaryKey(Article record);

    List<Article> selectByUser(String user);
}